### ISSUE TITLE
PEP 561 compatibility

### ISSUE THREAD

**Issue by Kaveshnikov** [expert-m/aiohttp-rpc#10]
Hello.
Thank you for your library. It saves us much time for RPC-API implementation. Unfortunately, It is not compatible with [PEP 561](https://www.python.org/dev/peps/pep-0561/), so we cannot use its type hints for type checking with mypy.

I can make a PR to fix this if you don't mind.

**Comment by expert-m** [comment]
Hi! I'm glad to hear you've found this library useful.


> I can make a PR to fix this if you don't mind.

Yes, that would be great.

**Comment by expert-m** [comment]
Thanks for PR. Your changes in https://pypi.org/project/aiohttp-rpc/1.0.0b1/

**Comment by Kaveshnikov** [comment]
Very well. I close the issue then.
