### ISSUE TITLE
WsJsonRpcClient callers not receiving ConnectionResetError

### ISSUE THREAD

**Issue by davidmcnabnz** [expert-m/aiohttp-rpc#12]
Within a `WsJsonRpcClient` async context, if an underlying socket connection fails _while one or more tasks' API calls are in progress_ (ie, taking a few seconds, with either a long timeout or no timeout) then all these waiting tasks just hang in limbo, and don't see any exceptions.

It seems there's no mechanism for detecting the connection has died, and then calling `.notify_all_about_error(exc)` to throw the relevant exception up the chain for all of the current pending callers.

Is there any way to ensure access to all relevant exceptions for tasks calling remote API methods on a `WsJsonRpcClient` websocket connection?

**Comment by davidmcnabnz** [comment]
As a workaround, I've done some heavy subclassing/overrides, including a 'keep-alive' task which periodically calls a `.ping()` method on the remote. If this call fails, the keep-alive task feeds the exception into `.notify_all_about_error()`, which is providing exception access to all pending method callers.

**Comment by davidmcnabnz** [comment]
@expert-m thanks for your rapid response to this issue.

It's been impacting production servers, so I'm keen to get a fix into the field ASAP.

Do you envisage a fast acceptance/merge of your PR into a new aiohttp_rpc release?
Or do you recommend applying your update into my field pending the new release?

**Comment by expert-m** [comment]
Thanks for finding the issue. I have prepared version `1.3.0b1` with the changes. You can use it.
