### ISSUE TITLE
WebSocket server can only handle one request at a time

### ISSUE THREAD

**Issue by layday** [expert-m/aiohttp-rpc#2]
The blocks until a response is sent meaning that the server can only handle one request a time:

https://github.com/expert-m/aiohttp-rpc/blob/135e2c6e080cd707ac626a9795e4ffd1e83adaab/aiohttp_rpc/server/websocket.py#L41

**Comment by expert-m** [comment]
Thank you for noticing this. I created [PR](https://github.com/expert-m/aiohttp-rpc/pull/3). You can check it.

**Comment by layday** [comment]
Thank you for the quick fix - looks good.  I made a small observation in the PR about the return value of `handle_http_request`.
