### ISSUE TITLE
Provide a way to send notification from the server

### ISSUE THREAD

**Issue by layday** [expert-m/aiohttp-rpc#4]
To deliver notifications from the server to the client, it's conventional for the server to act as a client by sending an `id`-less request to the client - the JSON-RPC spec defines a client as the origin of request and the server as the origin of response objects and either node can fill either one or both of those roles.  Would you consider providing a way for the server to send `Request` objects to the client?

**Comment by expert-m** [comment]
If I understood you correctly, then there is already this opportunity. You can process a request and send requests to others in the same code.

You can use this in the same code:
https://github.com/expert-m/aiohttp-rpc#http-server-example
https://github.com/expert-m/aiohttp-rpc#http-client-example

**Comment by layday** [comment]
Unless I'm missing something, there doesn't seem to be a way to send arbitrary requests (notifications) from the server to the client - you can only respond to a request with exactly one response.

**Comment by expert-m** [comment]
But you can write own middleware that will create `rpc_client` or write some decorator.

```python3
async def some_middleware(request: protocol.JsonRpcRequest, handler: typing.Callable) -> protocol.JsonRpcResponse:
    async with aiohttp_rpc.JsonRpcClient(...) as rpc_client:
        request.extra_args['rpc_client'] = rpc_client
        return await handler(request)

...

async def ping(rpc_request, rpc_client):
    await rpc_client.ping()
    await rpc_client.ping()
```

Or maybe you want something like that (it does not work now, but I can think about it):

```python3
async def ping(rpc_request):
    yield 'pong'
    yield 'pong'
    yield 'pong'
    yield 'pong'
    yield 'pong'
```

Can you provide examples? Maybe then I can help better.

**Comment by layday** [comment]
Well, that would require me to spawn a client in the request's call chain.  My client is already alive - what I want to do is send a message or several messages to it which look like requests rather than responses, during the lifetime of a request.  Something akin to:

```py
async def notify_middleware(
    request: JsonRpcRequest, handler: Callable[..., Any]
) -> JsonRpcResponse:
    async def notify(method: str, params: Mapping[str, Any]) -> None:
        # "notify" would construct a `JsonRpcRequest` with an "id" value of "null"
        # and send it to the client
        ...

    request.extra_args['notify'] = notify
    return await handler(request)

...

async def handle_request(
    rpc_request: JsonRpcRequest,
    notify: Callable[[str, Mapping[str, Any]], Awaitable[None]],
) -> JsonRpcResponse:
    for item in range(7):
        await notify(
            'status_report',
            {'status': f'processing item with number {item}'},
        )

    return {...}  # The actual "Response"

```

**Comment by expert-m** [comment]
```python3
async def notify(method: str, params: Mapping[str, Any]) -> None:
```
- You want to call a specific method on the client, but the client does not have a list of methods (and I think that not need to change). 

Addition to my examples with the message above:
1. You can use pattern `repository` in this example. It can reduce created clients.
2. I see that you want to send some progress. So I can propose this variant:
```python3
# Server
async def do_task(rpc_request):
    for item in range(7):
        yeild {'status': f'processing item with number {item}'}

# Client
async for result in rpc.do_task():
    print(result['status'])
```

**Comment by layday** [comment]
You are right, the client should not have methods.  However, the web client is able to function as a JSON-RPC server - the JSON-RPC 'server' does not have to map to a web server.  This sort of setup isn't possible with HTTP but it is possible with WebSockets.  My client is not in Python - it does not use `aiohttp-rpc` - so the proposed solution won't work for me.  I suppose I could just send a request to query for progress until I receive the result in the client, but I'd have to push the response state up the stack somehow, e.g. with `contextvars`.

**Comment by layday** [comment]
Ahem, I should've probably mentioned this is meant for use with WebSockets earlier.

**Comment by expert-m** [comment]
Hi! I added the feature (`ws_client_for_server_response`). Could you check #5?

**Comment by layday** [comment]
Thanks, will take a look as soon as I can :)

**Comment by expert-m** [comment]
There is the new feature in `0.7.0rc1`. If you still have questions about the feature or the code, you can create a new issue or write here. 

Glad to help you ;)
