### ISSUE TITLE
Custom aiohttp POST params

### ISSUE THREAD

**Issue by PaulWasTaken** [expert-m/aiohttp-rpc#7]
Hi, what do you think about possibility to pass params in aiohttp post request?
E.g, I want to pass my custom unique per request header or timeout.
I suppose, we can start from `direct_call` and `send_json`.
They can be modified this way:
```
async def direct_call(self, rpc_request: JsonRpcRequest, **kwargs) -> JsonRpcResponse:
```
and
```
async def send_json(self,
                        data: typing.Any, *,
                        without_response: bool = False, **kwargs) -> typing.Tuple[typing.Any, typing.Optional[dict]]:
        merged_kwargs = merge_kwargs(self.request_kwargs, kwargs) (IMO, kwargs should be prioritized)
        http_response = await self.session.post(self.url, json=data, **merged_kwargs)
```
The idea is, if you need some request customization, you will use `direct_call`, otherwise `call`.

**Comment by expert-m** [comment]
Yes, it's a good idea 👍. I'll create a pull request a little later.

**Comment by PaulWasTaken** [comment]
I'd like to help you. Is it possible? I mean, I've already tried to open PR, but 403 :(

**Comment by expert-m** [comment]
What did you do?
https://stackoverflow.com/questions/29044551/http-403-on-github-pull-request - maybe it will be useful

**Comment by PaulWasTaken** [comment]
Yep, my mistake, sorry

**Comment by expert-m** [comment]
Merged 👍
