### ISSUE TITLE
The aiohttp-rpc is not tagged with "Framework :: Aiohttp" classifier on Pypi 

### ISSUE THREAD

**Issue by Maillol** [expert-m/aiohttp-rpc#9]
Hello,

A MR on the pypa repository to add the classifier "Framework :: Aiohttp" is opened.

The PyPI moderators ask to have 10 (or more) other project maintainers submit comments on the requesting issue about their desire to use the "Framework :: Aiohttp" classifier on their already-published project.

Please could you add a comment with a link to your package on pypi:

https://github.com/pypa/trove-classifiers/issues/54

Thanks

**Comment by expert-m** [comment]
Yes, good idea
